# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jiaweideng/Documents/SVF/SVF-pybind11-master/SVF-Python

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jiaweideng/Documents/SVF/SVF-pybind11-master/SVF-Python

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jiaweideng/Documents/SVF/SVF-pybind11-master/SVF-Python/CMakeFiles /Users/jiaweideng/Documents/SVF/SVF-pybind11-master/SVF-Python//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jiaweideng/Documents/SVF/SVF-pybind11-master/SVF-Python/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named svfModule_pybind

# Build rule for target.
svfModule_pybind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 svfModule_pybind
.PHONY : svfModule_pybind

# fast build rule for target.
svfModule_pybind/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/build
.PHONY : svfModule_pybind/fast

src/srcPybind/pybind_module.o: src/srcPybind/pybind_module.cpp.o
.PHONY : src/srcPybind/pybind_module.o

# target to build an object file
src/srcPybind/pybind_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/src/srcPybind/pybind_module.cpp.o
.PHONY : src/srcPybind/pybind_module.cpp.o

src/srcPybind/pybind_module.i: src/srcPybind/pybind_module.cpp.i
.PHONY : src/srcPybind/pybind_module.i

# target to preprocess a source file
src/srcPybind/pybind_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/src/srcPybind/pybind_module.cpp.i
.PHONY : src/srcPybind/pybind_module.cpp.i

src/srcPybind/pybind_module.s: src/srcPybind/pybind_module.cpp.s
.PHONY : src/srcPybind/pybind_module.s

# target to generate assembly for a file
src/srcPybind/pybind_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/src/srcPybind/pybind_module.cpp.s
.PHONY : src/srcPybind/pybind_module.cpp.s

src/svfModule/svfModule.o: src/svfModule/svfModule.cpp.o
.PHONY : src/svfModule/svfModule.o

# target to build an object file
src/svfModule/svfModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/src/svfModule/svfModule.cpp.o
.PHONY : src/svfModule/svfModule.cpp.o

src/svfModule/svfModule.i: src/svfModule/svfModule.cpp.i
.PHONY : src/svfModule/svfModule.i

# target to preprocess a source file
src/svfModule/svfModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/src/svfModule/svfModule.cpp.i
.PHONY : src/svfModule/svfModule.cpp.i

src/svfModule/svfModule.s: src/svfModule/svfModule.cpp.s
.PHONY : src/svfModule/svfModule.s

# target to generate assembly for a file
src/svfModule/svfModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/svfModule_pybind.dir/build.make CMakeFiles/svfModule_pybind.dir/src/svfModule/svfModule.cpp.s
.PHONY : src/svfModule/svfModule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... svfModule_pybind"
	@echo "... src/srcPybind/pybind_module.o"
	@echo "... src/srcPybind/pybind_module.i"
	@echo "... src/srcPybind/pybind_module.s"
	@echo "... src/svfModule/svfModule.o"
	@echo "... src/svfModule/svfModule.i"
	@echo "... src/svfModule/svfModule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

